"""Portfolio repository ports."""
from __future__ import annotations
import uuid
from abc import ABC, abstractmethod
from app.domain.portfolio.entities import Client, PortfolioAccount, Trade, Order


class ClientRepository(ABC):
    @abstractmethod
    def add(self, client: Client) -> None: ...
    @abstractmethod
    def get(self, client_id: uuid.UUID) -> Client | None: ...
    @abstractmethod
    def get_by_pan_hash(self, pan_hash: str) -> Client | None: ...
    @abstractmethod
    def get_by_onboarding_id(self, app_id: uuid.UUID) -> Client | None: ...


class PortfolioAccountRepository(ABC):
    @abstractmethod
    def add(self, account: PortfolioAccount) -> None: ...
    @abstractmethod
    def get(self, account_id: uuid.UUID) -> PortfolioAccount | None: ...
    @abstractmethod
    def list_by_client(self, client_id: uuid.UUID) -> list[PortfolioAccount]: ...
    @abstractmethod
    def update(self, account: PortfolioAccount) -> None: ...


class TradeRepository(ABC):
    @abstractmethod
    def add(self, trade: Trade) -> None: ...
    @abstractmethod
    def list_by_portfolio(self, portfolio_id: uuid.UUID, *, limit: int = 50) -> list[Trade]: ...


class OrderRepository(ABC):
    @abstractmethod
    def add(self, order: Order) -> None: ...
    @abstractmethod
    def get(self, order_id: uuid.UUID) -> Order | None: ...
    @abstractmethod
    def update(self, order: Order) -> None: ...
    @abstractmethod
    def list_by_strategy(self, strategy_id: uuid.UUID) -> list[Order]: ...
